#!/usr/bin/env python3
"""
Cross-phase comparison report generator.

Scans evaluation_metrics.txt and interaction_metrics.txt across all phase
run directories, finds the best epoch per phase, and produces a unified
Markdown comparison report.

Usage:
  python tools/cross_phase_report.py [--output docs/cross_phase_comparison.md]
"""

import os
import re
import argparse

PHASE_CONFIGS = {
    "Phase 0 (Additive)": {
        "project_dir": "/data1/yangzhuowei/MambaTalk_dual_phase_1",
        "run": "0323_085201_phase0_additive",
    },
    "Phase 1 (InterFusion)": {
        "project_dir": "/data1/yangzhuowei/MambaTalk_dual_phase_1",
        "run": "0323_092535_phase1_interaction",
    },
    "Phase 2 (+State)": {
        "project_dir": "/data1/yangzhuowei/MambaTalk_dual_phase_2",
        "run": "0323_161327_phase2_state",
    },
    "Phase 3 (+MultiLevel)": {
        "project_dir": "/data1/yangzhuowei/MambaTalk_dual_phase_3",
        "run": "0324_055633_phase3_multilevel",
    },
}

EVAL_METRICS = ["FGD", "L1Div", "BC", "MPJPE"]
INTERACTION_METRICS = ["IS", "PeakLag", "TRS", "PMC"]
SIGMA_NAMES = ["sigma_self", "sigma_partner", "sigma_state"]


def parse_eval_metrics(filepath):
    """Parse evaluation_metrics.txt into a dict."""
    metrics = {}
    if not os.path.exists(filepath):
        return metrics
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            for key in EVAL_METRICS + ["MSEFace", "LVDFace"]:
                pat = rf"{key}:\s+([\d.eE+-]+|N/A)"
                m = re.search(pat, line)
                if m and m.group(1) != "N/A":
                    metrics[key] = float(m.group(1))
    return metrics


def parse_interaction_metrics(filepath):
    """Parse interaction_metrics.txt into a dict."""
    metrics = {}
    if not os.path.exists(filepath):
        return metrics
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            for key in INTERACTION_METRICS:
                pat = rf"{key}:\s+([\d.eE+-]+)"
                m = re.search(pat, line)
                if m:
                    metrics[key] = float(m.group(1))
    return metrics


def parse_sigma_analysis(filepath):
    """Parse sigma_analysis.txt global averages."""
    metrics = {}
    if not os.path.exists(filepath):
        return metrics
    with open(filepath) as f:
        for line in f:
            for name in SIGMA_NAMES:
                if name in line:
                    m = re.search(rf":\s+([\d.]+)", line)
                    if m:
                        metrics[name] = float(m.group(1))
    return metrics


def find_best_epoch(run_base, metric="FGD", lower_is_better=True):
    """Scan epoch subdirs for the best metric value."""
    best_ep, best_val, best_metrics = None, None, {}
    if not os.path.isdir(run_base):
        return best_ep, best_metrics

    for entry in os.listdir(run_base):
        ep_dir = os.path.join(run_base, entry)
        if not os.path.isdir(ep_dir) or not entry.isdigit():
            continue
        eval_path = os.path.join(ep_dir, "evaluation_metrics.txt")
        m = parse_eval_metrics(eval_path)
        if metric not in m:
            continue
        val = m[metric]
        if best_val is None or (lower_is_better and val < best_val) or (not lower_is_better and val > best_val):
            best_val = val
            best_ep = int(entry)
            best_metrics = m

    return best_ep, best_metrics


def generate_report(output_path):
    """Generate the full cross-phase Markdown report."""
    lines = []
    lines.append("# Dual-Person Gesture Generation Cross-Phase Comparison Report\n")
    lines.append(f"> Auto-generated by `tools/cross_phase_report.py`\n")

    all_phase_data = {}

    for phase_name, cfg in PHASE_CONFIGS.items():
        run_base = os.path.join(cfg["project_dir"], "outputs/audio2pose/custom", cfg["run"])
        best_ep, eval_m = find_best_epoch(run_base, metric="FGD", lower_is_better=True)

        inter_m = {}
        sigma_m = {}
        if best_ep is not None:
            ep_dir = os.path.join(run_base, str(best_ep))
            inter_m = parse_interaction_metrics(os.path.join(ep_dir, "interaction_metrics.txt"))
            sigma_m = parse_sigma_analysis(os.path.join(ep_dir, "sigma_analysis.txt"))

        all_phase_data[phase_name] = {
            "epoch": best_ep,
            "eval": eval_m,
            "interaction": inter_m,
            "sigma": sigma_m,
            "run": cfg["run"],
        }

    # --- Table 1: Single-speaker quality ---
    lines.append("## Single-Speaker Quality Metrics (evaluate_v2)\n")
    lines.append("| Phase | Best Epoch | FGD (lower=better) | L1Div (higher=better) | BC (higher=better) | MPJPE (lower=better) |")
    lines.append("|-------|-----------|------|--------|-----|--------|")
    for phase_name, d in all_phase_data.items():
        ep = d["epoch"] if d["epoch"] is not None else "N/A"
        fgd = f'{d["eval"].get("FGD", float("nan")):.4f}' if "FGD" in d["eval"] else "N/A"
        l1 = f'{d["eval"].get("L1Div", float("nan")):.4f}' if "L1Div" in d["eval"] else "N/A"
        bc = f'{d["eval"].get("BC", float("nan")):.4f}' if "BC" in d["eval"] else "N/A"
        mpjpe = f'{d["eval"].get("MPJPE", float("nan")):.4f}' if "MPJPE" in d["eval"] else "N/A"
        lines.append(f"| {phase_name} | {ep} | {fgd} | {l1} | {bc} | {mpjpe} |")
    lines.append("")

    # --- Table 2: Interaction quality ---
    lines.append("## Dual-Person Interaction Metrics (evaluate_interaction)\n")
    lines.append("| Phase | IS (higher=better) | PeakLag(s) | TRS (higher=better) | PMC (higher=better) |")
    lines.append("|-------|-----|-----------|------|------|")
    for phase_name, d in all_phase_data.items():
        im = d["interaction"]
        is_v = f'{im["IS"]:.4f}' if "IS" in im else "N/A"
        lag = f'{im["PeakLag"]:.4f}' if "PeakLag" in im else "N/A"
        trs = f'{im["TRS"]:.4f}' if "TRS" in im else "N/A"
        pmc = f'{im["PMC"]:.4f}' if "PMC" in im else "N/A"
        lines.append(f"| {phase_name} | {is_v} | {lag} | {trs} | {pmc} |")
    lines.append("")

    # --- Table 3: Sigma weights ---
    lines.append("## InteractionFusion Sigma Weight Analysis (Phase 1-3)\n")
    lines.append("| Phase | sigma_self | sigma_partner | sigma_state |")
    lines.append("|-------|-----------|--------------|-------------|")
    for phase_name, d in all_phase_data.items():
        sm = d["sigma"]
        if sm:
            lines.append(f"| {phase_name} | {sm.get('sigma_self', 0):.4f} | "
                         f"{sm.get('sigma_partner', 0):.4f} | {sm.get('sigma_state', 0):.4f} |")
        else:
            lines.append(f"| {phase_name} | N/A | N/A | N/A |")
    lines.append("")

    # --- Ablation conclusions placeholder ---
    lines.append("## Ablation Conclusions\n")
    p0 = all_phase_data.get("Phase 0 (Additive)", {}).get("eval", {})
    p1 = all_phase_data.get("Phase 1 (InterFusion)", {}).get("eval", {})
    p2 = all_phase_data.get("Phase 2 (+State)", {}).get("eval", {})
    p3 = all_phase_data.get("Phase 3 (+MultiLevel)", {}).get("eval", {})

    if "FGD" in p0 and "FGD" in p1:
        delta = (p0["FGD"] - p1["FGD"]) / (p0["FGD"] + 1e-8) * 100
        verdict = "EFFECTIVE" if delta > 5 else "MARGINAL" if delta > 0 else "NOT EFFECTIVE"
        lines.append(f"- **InteractionFusion vs Additive**: FGD delta = {delta:.1f}% -> {verdict}")
    else:
        lines.append("- **InteractionFusion vs Additive**: Awaiting evaluation data")

    if "FGD" in p1 and "FGD" in p2:
        delta = (p1["FGD"] - p2["FGD"]) / (p1["FGD"] + 1e-8) * 100
        verdict = "EFFECTIVE" if delta > 5 else "MARGINAL" if delta > 0 else "NOT EFFECTIVE"
        lines.append(f"- **State conditioning**: FGD delta = {delta:.1f}% -> {verdict}")
    else:
        lines.append("- **State conditioning**: Awaiting evaluation data")

    if "FGD" in p2 and "FGD" in p3:
        delta = (p2["FGD"] - p3["FGD"]) / (p2["FGD"] + 1e-8) * 100
        verdict = "EFFECTIVE" if delta > 5 else "MARGINAL" if delta > 0 else "NOT EFFECTIVE"
        lines.append(f"- **Multi-level injection**: FGD delta = {delta:.1f}% -> {verdict}")
    else:
        lines.append("- **Multi-level injection**: Awaiting evaluation data")

    lines.append("")

    report = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(report)
    print(report)
    print(f"\nReport saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Generate cross-phase comparison report')
    parser.add_argument('--output', default='docs/cross_phase_comparison.md',
                        help='Output Markdown file path')
    args = parser.parse_args()
    generate_report(args.output)


if __name__ == '__main__':
    main()
